apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidemo-deployment
spec:
  selector:
    matchLabels:
      app: apidemo-pod
  template:
    metadata:
      labels:
        app: apidemo-pod
    spec:
      containers:
      - name: apidemo-container
        image: apidemo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
