apiVersion: v1
kind: Service
metadata:
  name: {{ template "apidemo.fullname" . }}
  labels:
    app: {{ template "apidemo.name" . }}
    chart: {{ template "apidemo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "apidemo.name" . }}
    release: {{ .Release.Name }}
